### ISSUE TITLE
SignIn failed with code:: 12502

### ISSUE THREAD

**Issue by marcelodiaz558** [chlegou/bitbot#9] opened 2020-08-08 21:51 UTC
The Google Auth sign in doesn't work with the release V1.4.6 rc3 installed. The auto roll isn't working for me anymore with the Google Play version. I'm using a Nokia 2,2 with the most recent update from Google.

**Comment by Bolek719** [comment] 2020-08-09 23:18
1

**Comment by Bolek719** [comment] 2020-08-09 23:18
Duplicate of #`

**Closed** 2020-08-13 09:30 UTC
